CREATE TABLE fits (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) UNIQUE NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_fits_modtime BEFORE UPDATE ON fits FOR EACH ROW EXECUTE FUNCTION update_modified_column();

ALTER TABLE products ADD COLUMN fit_id UUID REFERENCES fits(id) ON DELETE SET NULL;
